name: bckgrnd
description: "bckgrnd app."
publish_to: 'none'

version: 1.0.0+1

platforms:
  android:
  ios:
  macos:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.1

  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.4
  record: ^5.1.2
  wav: ^1.3.0
  cupertino_icons: ^1.0.8
  whisper_flutter_new: ^1.0.1
  observable: ^0.24.0
  permission_handler: ^11.3.1

  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.3.2
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/